version: 2
project_name: autoDrops
before:
  hooks:
    - go mod tidy
builds:
  - id: autoDrops
    main: .
    binary: autoDrops
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - windows
    goarch:
      - 386
      - amd64
      - arm64
archives:
  - id: autoDrops_windows
    ids:
      - autoDrops
    formats:
      - zip
    name_template: '{{ .ProjectName }}-{{- if eq .Arch "386" }}x86{{- else if eq .Arch "amd64" }}x64{{- else }}{{ .Arch }}{{- end }}-{{ .Tag }}'
    files:
      - profile.yml
      - Readme.md
      - LICENCE
    wrap_in_directory: true
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: auto
